name: Python CI

on:
  push:
    branches: ['main']
  
  
jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      #STEP 1: CHECKOUT THE REPOSITORY
      - uses: actions/checkout@v4

      #STEP 2: Install python on the runner
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      #Step 3: Install dependencies
      - name: Install dependencies
        run: python -m pip intall unittest

          #Step 4: Run tests
      - name: Run unit tests
        #If using unittest:
        run: python -m unitttest test.py